### ISSUE TITLE
Implement function to create a customer resource

### ISSUE THREAD

**Issue by TestSubjector** [CSCI-GA-2820-FA22-003/customers#3] opened 2022-09-30 20:07 UTC
**As a** Developer
**I need** a function that can create a customer object for the eCommerce web site
**So that** I can store the details associated with the new customer.

 ### Assumptions
- Development environment is setup
- Knowledge of Python
- Access to Database schema

### Acceptance Criteria
 ```gherkin
 Given a request to add a new customer
 When the create function is invoked
 Then the database is updated with details of the new customer
 ```

**Comment by mm12063** [comment] 2022-10-03 21:05
Duplicate of #6

**Closed as completed by mm12063** 2022-10-03 21:06 UTC
Labels: duplicate, enhancement
