### ISSUE TITLE
Setup yaml files for Github Actions

### ISSUE THREAD

**Issue by TestSubjector** [CSCI-GA-2820-FA22-003/customers#37] opened 2022-11-01 11:48 UTC
**As a** developer
**I need** to create the required .yaml files in the _.github/workflows/_ directory
**So that** we define the workflow to run by GitHub Actions for each pull request/push to master.

 ### Assumptions
- GitHub Action workflow is created
- Knowledge to create a workflow using different .yaml files 
- Required files: ci.yaml and cd.yaml

### Acceptance Criteria
 ```gherkin
 Given the .yaml files are setup
 When Github Actions runs it automated CI/CD builds
 Then the configuration of the builds are as per the specifications contained in the .yaml files
 ```

**Comment by KaterinPerdom** [comment] 2022-11-13 01:25
@TestSubjector @mm12063 
I'm confused, i think this problem is duplicate of #58 
could you confirm me ?

**Comment by TestSubjector** [comment] 2022-11-13 02:21
Issue #58 is the CI part of this story. The CD part is still left. That is we need to add a pipeline to deploy the service to the IBM Cloud automatically. Then it should run our TDD unit tests and then the BDD integration tests (not written yet)..

We can close this issue (as a dup) and then make new story for the CD part.

**Closed as completed** 2022-11-13 02:38 UTC
Labels: duplicate, invalid
